# Generated by Django 4.2.7 on 2025-09-03 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'url'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checks', models.IntegerField(default=0)),
                ('successful_checks', models.IntegerField(default=0)),
                ('failed_checks', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('average_load_time', models.FloatField(default=0.0)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(default=0.0)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='webmonitor.website')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('load_time', models.FloatField(help_text='Page load time in seconds')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('connection_error', 'Connection Error')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='webmonitor.website')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['website', '-timestamp'], name='webmonitor__website_190bb4_idx'), models.Index(fields=['status', '-timestamp'], name='webmonitor__status_f0ec7e_idx')],
            },
        ),
    ]
